-- MySQL Script generated by MySQL Workbench
-- Tue Oct  3 13:39:52 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`direcciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`direcciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `calle` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `localidad` VARCHAR(45) NOT NULL,
  `partido` VARCHAR(45) NOT NULL,
  `codigo_postal` VARCHAR(45) NULL,
  `latitud` VARCHAR(45) NULL,
  `longitud` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_1` VARCHAR(45) NOT NULL,
  `nombre_2` VARCHAR(45) NULL,
  `apellido_1` VARCHAR(45) NOT NULL,
  `apellido_2` VARCHAR(45) NULL,
  `foto` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `estado` INT NOT NULL,
  `fecha_creacion` DATETIME NULL,
  `direcciones_id` INT NOT NULL,
  PRIMARY KEY (`id`, `direcciones_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_usuarios_direcciones1_idx` (`direcciones_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_direcciones1`
    FOREIGN KEY (`direcciones_id`)
    REFERENCES `mydb`.`direcciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ubicaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ubicaciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `telefono` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NULL,
  `foto` VARCHAR(45) NULL,
  `direcciones_id` INT NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  PRIMARY KEY (`id`, `direcciones_id`),
  INDEX `fk_ubicaciones_direcciones1_idx` (`direcciones_id` ASC) VISIBLE,
  CONSTRAINT `fk_ubicaciones_direcciones1`
    FOREIGN KEY (`direcciones_id`)
    REFERENCES `mydb`.`direcciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`accion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`accion` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `accion_id` INT NOT NULL,
  PRIMARY KEY (`id`, `accion_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_roles_accion1_idx` (`accion_id` ASC) VISIBLE,
  CONSTRAINT `fk_roles_accion1`
    FOREIGN KEY (`accion_id`)
    REFERENCES `mydb`.`accion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios_x_ubicaciones_x_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios_x_ubicaciones_x_roles` (
  `id` INT NOT NULL,
  `usuarios_id` INT NOT NULL,
  `ubicaciones_id` INT NOT NULL,
  `roles_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuarios_id`, `ubicaciones_id`, `roles_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `fk_usuarios_x_ubicaciones_usuarios1_idx` (`usuarios_id` ASC) ,
  INDEX `fk_usuarios_x_ubicaciones_ubicaciones1_idx` (`ubicaciones_id` ASC) ,
  INDEX `fk_usuarios_x_ubicaciones_roles1_idx` (`roles_id` ASC) ,
  CONSTRAINT `fk_usuarios_x_ubicaciones_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `mydb`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_x_ubicaciones_ubicaciones1`
    FOREIGN KEY (`ubicaciones_id`)
    REFERENCES `mydb`.`ubicaciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_x_ubicaciones_roles1`
    FOREIGN KEY (`roles_id`)
    REFERENCES `mydb`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`datalogger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`datalogger` (
  `id` INT NOT NULL,
  `direccion_mac` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NULL,
  `foto` VARCHAR(45) NULL,
  `entrada01_id` INT NULL,
  `entrada01_nombre` VARCHAR(45) NULL,
  `entrada01_descripcion` VARCHAR(100) NULL,
  `entrada02_id` INT NULL,
  `entrada02_nombre` VARCHAR(45) NULL,
  `entrada02_descripcion` VARCHAR(100) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dataloggers_x_ubicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dataloggers_x_ubicacion` (
  `id` INT NOT NULL,
  `ubicaciones_id` INT NOT NULL,
  `datalogger_id` INT NOT NULL,
  PRIMARY KEY (`id`, `ubicaciones_id`, `datalogger_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_dataloggers_x_ubicacion_ubicaciones1_idx` (`ubicaciones_id` ASC) VISIBLE,
  INDEX `fk_dataloggers_x_ubicacion_datalogger1_idx` (`datalogger_id` ASC) VISIBLE,
  CONSTRAINT `fk_dataloggers_x_ubicacion_ubicaciones1`
    FOREIGN KEY (`ubicaciones_id`)
    REFERENCES `mydb`.`ubicaciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dataloggers_x_ubicacion_datalogger1`
    FOREIGN KEY (`datalogger_id`)
    REFERENCES `mydb`.`datalogger` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
