GET  http://localhost:3002/alarms/all
Content-Type: application/json

###
GET  http://localhost:3002/alarms/3
Content-Type: application/json

###
POST http://localhost:3002/alarms/add
Content-Type: application/json

{ 
  "channelid": 11,
  "table": "guemes",
  "column": "d6",
  "name": "Bomba 1 - Tiempo de funcionamiento",
  "description": "Mide el tiempo de funcionamiento de la bomba 1 del guemes",
  "max": 50,
  "min": 0,
  "timeperiod": "1 HOUR"
}

###

POST http://localhost:3002/alarms/update/4
Content-Type: application/json

{
  "dataloggerID": 1,
  "channelId": 11,
  "table": "guemes",
  "column": "d6",
  "name": "Bomba 1 - MAXIMO 60% ON",
  "description": "Se activa si sobrepasa el limite de 60% de funcionamiento en la ultima hora.",
  "max": 60,
  "min": 0,
  "state": true,
  "timePeriod": "1 HOUR"
}

###

POST http://localhost:3002/alarms/updatestate/1
Content-Type: application/json

{  
  "estado": true,
  "nombre": "guemes - compresor 1",
  "datalogger_id": 1,
  "channel_id": 10 
}

###

DELETE  http://localhost:3002/alarms/delete/52
Content-Type: application/json

###

POST http://localhost:3002/alarms/3/users/7/add
Content-Type: application/json

###
GET  http://localhost:3002/alarms/users/all
Content-Type: application/json

###
GET  http://localhost:3002/alarms/1/users/all
Content-Type: application/json

###
GET http://localhost:3002/alarms/logs/all
Content-Type: application/json
###
GET http://localhost:3002/alarms/logs/users/32
Content-Type: application/json
###
GET http://localhost:3002/alarms/logs/channels/11
Content-Type: application/json