fecha: '2023-10-10 11:11:18'
identificador:30839807218
tiempo_total:300
d1_estado:1
d1_cantidad:5
d1_tiempo:120
d2_estado:0
d2_cantidad:3
d2_tiempo:90
d3_estado:1
d3_cantidad:2
d3_tiempo:60
d4_estado:0
d4_cantidad:0
d4_tiempo:0
d5_estado:1
d5_cantidad:4
d5_tiempo:150
d6_estado:0
d6_cantidad:0
d6_tiempo:0
d7_estado:1
d7_cantidad:1
d7_tiempo:30
d8_estado:0
d8_cantidad:0
d8_tiempo:0
a1_inst:10
a1_min:5
a1_max:20
a1_estado:1
a1_cantidad:2
a1_tiempo:45
a2_inst:15
a2_min:10
a2_max:25
a2_estado:0
a2_cantidad:1
a2_tiempo:30
a3_inst:25
a3_min:20
a3_max:30
a3_estado:1
a3_cantidad:3
a3_tiempo:60
a4_inst:18
a4_min:15
a4_max:22
a4_estado:0
a4_cantidad:0
a4_tiempo:0
a5_inst:30
a5_min:25
a5_max:35
a5_estado:1
a5_cantidad:2
a5_tiempo:40
servicio:1
energia:0
texto: "Datos de prueba - trama Ok"